[package]
name = "wild"
version = "0.1.0"
authors = ["Clemens Wasser <clemens.wasser@gmail.com>"]
edition = "2018"

[dependencies]
ash = "0.31"
winit = "0.24"
ash-window = "0.5"
cgmath = "0.17"
memoffset = "0.6"
