[package]
name = "wild"
version = "0.1.0"
authors = ["Clemens Wasser <clemens.wasser@gmail.com>"]
edition = "2018"

[dependencies]
ash = "0.31.0"
winit = "0.24.0"
ash-window = "0.5.0"
cgmath = "0.17.0"
memoffset = "0.6.1"
